apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pg-monitoring
  labels:
    app: pg-monitoring
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: pg-monitoring
              image: postgres:10.3-alpine
              args:
                - psql
                - -h
                - postgres
                - -U
                - postgres
                - -c
                - "SELECT * FROM pg_statio_user_tables;"
              env:
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: mysecret
                      key: postgres_password
          restartPolicy: OnFailure
