apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  postgres_password: bWF0dGVybW9zdA==
  mattermost_db_password: bWF0dGVybW9zdA==
  monitoring_db_password: bW9uaXRvcmluZw==
  backup_db_password: YmFja3Vw
